name: PerformProductivity
favicon: null
layout_spectrum: 0.31172920600511134
typography_spectrum: 0.3375114619266242
title: Perform Productivity Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#337abc'
    - '#999999'
    - '#9abdde'
    - '#bcdbe9'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
